import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navbar md:mx-28">
          <Navbar />
        </nav>
        <main className="main-container mx-10  md:mx-32 mt-10">
          {children}
        </main>
        <footer className=" footer  mt-32">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
