import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="navbar">
          <Navbar />
        </header>
        <main className="main-container mx-10 md:mx-32 lg:mx-44 mt-10">{children}</main>
        <footer className="mx-5 footer mt-32">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
